//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAI.BusinessLogic.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Firm
    {
        public Firm()
        {
            this.Inspections = new HashSet<Inspection>();
            this.Insurances = new HashSet<Insurance>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public string House { get; set; }
        public string Owner_Name { get; set; }
        public string Owner_Surname { get; set; }
        public Nullable<System.DateTime> Registration_Date { get; set; }
        public Nullable<bool> Deleted { get; set; }
    
        public virtual ICollection<Inspection> Inspections { get; set; }
        public virtual ICollection<Insurance> Insurances { get; set; }
    }
}
