//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAI.BusinessLogic.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GAIEntities : DbContext
    {
        public GAIEntities()
            : base("name=GAIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Firm> Firms { get; set; }
        public DbSet<Inspection> Inspections { get; set; }
        public DbSet<Insurance> Insurances { get; set; }
        public DbSet<Offense> Offenses { get; set; }
        public DbSet<Offense_Type> Offense_Type { get; set; }
        public DbSet<Owner> Owners { get; set; }
        public DbSet<PoliceDepartment> PoliceDepartments { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<Transport> Transports { get; set; }
    }
}
