//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAI.BusinessLogic.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspection
    {
        public int Id { get; set; }
        public Nullable<int> Id_Transport { get; set; }
        public Nullable<int> Id_Firm { get; set; }
        public Nullable<System.DateTime> Inspection_Date { get; set; }
        public Nullable<System.DateTime> Duration_Time { get; set; }
        public Nullable<bool> Deleted { get; set; }
    
        public virtual Firm Firm { get; set; }
        public virtual Transport Transport { get; set; }
    }
}
