//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAI.BusinessLogic.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transport
    {
        public Transport()
        {
            this.Inspections = new HashSet<Inspection>();
            this.Insurances = new HashSet<Insurance>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Id_Police_Department { get; set; }
        public Nullable<int> Id_Owner { get; set; }
        public string License_Plates { get; set; }
        public string Brand_Model { get; set; }
        public Nullable<System.DateTime> Creation_Date { get; set; }
        public string Color { get; set; }
        public Nullable<int> Carcass { get; set; }
        public string Type { get; set; }
        public Nullable<int> Max_Weight { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> Deleted { get; set; }
    
        public virtual ICollection<Inspection> Inspections { get; set; }
        public virtual ICollection<Insurance> Insurances { get; set; }
        public virtual Owner Owner { get; set; }
        public virtual PoliceDepartment PoliceDepartment { get; set; }
    }
}
